package com.didi.virtualapk.collector.res
/**
 * Represent a resource entry(e.g. drawable, anim, attr, layout...) in android project,
 * the information in this class will be recorded in the arsc file.
 *
 * @author zhengtao
 */
class ResourceEntry {

    /**
     * Type of a resource entry, e.g. drawable
     */
    String resourceType
    /**
     * Name of a resource entry, e.g. abc_btn_check_material is name of a drawable
     */
    String resourceName
    /**
     * Original id value of a resource entry, generated by aapt
     */
    int resourceId

    public ResourceEntry(resType, resName, resId) {
        resourceType = resType
        resourceName = resName
        resourceId = resId
    }

    /**
     * @return the hexadecimal resource id
     */
    public String getHexResourceId() {
        return "0x${Integer.toHexString(resourceId)}"
    }


    boolean equals(o) {
        if (this.is(o)) return true
        if (getClass() != o.class) return false

        ResourceEntry that = (ResourceEntry) o

        if (resourceName != that.resourceName) return false
        if (resourceType != that.resourceType) return false

        return true
    }


    int hashCode() {
        int result
        result = resourceType.hashCode()
        result = 31 * result + resourceName.hashCode()
        return result
    }
}